const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const cors = require('cors');
const app = express();
app.use(cors());
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: '*' } });
let openChallenges = [];
let activeMatches = {};
const W=340,H=580,PL=20,PR=320,PT=44,PB=536,GTL=126,GBL=214,GW=20,DISC_R=18,BALL_R=11,FRICTION=0.985,WALL_B=0.55,WIN=3;
function createDiscs(){const bp=[{x:170,y:456},{x:115,y:396},{x:225,y:396},{x:80,y:326},{x:260,y:326}];const rp=[{x:170,y:124},{x:115,y:184},{x:225,y:184},{x:80,y:254},{x:260,y:254}];const d=[];bp.forEach((p,i)=>d.push({x:p.x,y:p.y,vx:0,vy:0,r:DISC_R,team:0,id:i,startX:p.x,startY:p.y}));rp.forEach((p,i)=>d.push({x:p.x,y:p.y,vx:0,vy:0,r:DISC_R,team:1,id:i+5,startX:p.x,startY:p.y}));return d;}
function resetAfterGoal(m){m.ball={x:170,y:290,vx:0,vy:0,r:BALL_R};m.discs.forEach(d=>{d.x=d.startX;d.y=d.startY;d.vx=0;d.vy=0;});}
function dist(a,b){return Math.sqrt((a.x-b.x)**2+(a.y-b.y)**2);}
function resolveCol(a,b){const dx=b.x-a.x,dy=b.y-a.y,d=dist(a,b),mn=a.r+b.r;if(d<mn&&d>0){const nx=dx/d,ny=dy/d,ov=(mn-d)/2;a.x-=nx*ov;a.y-=ny*ov;b.x+=nx*ov;b.y+=ny*ov;const rv=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rv<0){a.vx+=rv*0.85*nx;a.vy+=rv*0.85*ny;b.vx-=rv*0.85*nx;b.vy-=rv*0.85*ny;}}}
function physicsStep(m){const all=[...m.discs,m.ball];all.forEach(o=>{o.x+=o.vx;o.y+=o.vy;o.vx*=FRICTION;o.vy*=FRICTION;if(Math.abs(o.vx)<0.02)o.vx=0;if(Math.abs(o.vy)<0.02)o.vy=0;if(o!==m.ball){if(o.x-o.r<PL){o.x=PL+o.r;o.vx*=-WALL_B;}if(o.x+o.r>PR){o.x=PR-o.r;o.vx*=-WALL_B;}if(o.y-o.r<PT){o.y=PT+o.r;o.vy*=-WALL_B;}if(o.y+o.r>PB){o.y=PB-o.r;o.vy*=-WALL_B;}}else{const iT=o.y-o.r<PT&&o.x>GTL&&o.x<GBL;const iB=o.y+o.r>PB&&o.x>GTL&&o.x<GBL;if(o.x-o.r<PL){o.x=PL+o.r;o.vx*=-WALL_B;}if(o.x+o.r>PR){o.x=PR-o.r;o.vx*=-WALL_B;}if(!iT){if(o.y-o.r<PT){o.y=PT+o.r;o.vy*=-WALL_B;}}if(!iB){if(o.y+o.r>PB){o.y=PB-o.r;o.vy*=-WALL_B;}}}});for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++)resolveCol(all[i],all[j]);}
function checkGoal(m){const b=m.ball;if(b.y-b.r<PT-GW&&b.x>GTL&&b.x<GBL)return 0;if(b.y+b.r>PB+GW&&b.x>GTL&&b.x<GBL)return 1;return -1;}
function allStopped(m){return![...m.discs,m.ball].some(o=>Math.abs(o.vx)>0.08||Math.abs(o.vy)>0.08);}
function runMatchLoop(matchId){const m=activeMatches[matchId];if(!m)return;m.wasStopped=false;m.interval=setInterval(()=>{const mm=activeMatches[matchId];if(!mm){clearInterval(m.interval);return;}if(mm.goalCooldown>0){mm.goalCooldown--;return;}physicsStep(mm);const st=checkGoal(mm);if(st>=0){mm.score[st]++;mm.goalCooldown=90;mm.wasStopped=false;const ct=st===0?1:0;mm.turn=ct;io.to(mm.player1).emit('goal_event',{score:mm.score,scoringTeam:st});io.to(mm.player2).emit('goal_event',{score:mm.score,scoringTeam:st});setTimeout(()=>{const mmm=activeMatches[matchId];if(!mmm)return;resetAfterGoal(mmm);mmm.goalCooldown=0;mmm.wasStopped=true;if(mmm.score[0]>=WIN||mmm.score[1]>=WIN){io.to(mmm.player1).emit('match_over_result',{score:mmm.score});io.to(mmm.player2).emit('match_over_result',{score:mmm.score});clearInterval(mmm.interval);delete activeMatches[matchId];return;}io.to(mmm.player1).emit('ball_reset',{ball:mmm.ball,score:mmm.score,playerTurn:mmm.turn===0,discs:mmm.discs.map(d=>({id:d.id,x:d.x,y:d.y}))});io.to(mmm.player2).emit('ball_reset',{ball:mmm.ball,score:mmm.score,playerTurn:mmm.turn===1,discs:mmm.discs.map(d=>({id:d.id,x:d.x,y:d.y}))});},1800);}const stopped=allStopped(mm);if(stopped&&!mm.wasStopped&&!mm.goalCooldown){mm.wasStopped=true;mm.turn=mm.turn===0?1:0;io.to(mm.player1).emit('your_turn',{playerTurn:mm.turn===0});io.to(mm.player2).emit('your_turn',{playerTurn:mm.turn===1});}else if(!stopped){mm.wasStopped=false;}io.to(mm.player1).emit('game_state',{ball:mm.ball,discs:mm.discs.map(d=>({id:d.id,x:d.x,y:d.y,vx:d.vx,vy:d.vy}))});io.to(mm.player2).emit('game_state',{ball:mm.ball,discs:mm.discs.map(d=>({id:d.id,x:d.x,y:d.y,vx:d.vx,vy:d.vy}))});},1000/60);}
io.on('connection',(socket)=>{socket.on('get_challenges',()=>{socket.emit('challenges_list',openChallenges);});socket.on('create_challenge',(data)=>{openChallenges=openChallenges.filter(c=>c.socketId!==socket.id);openChallenges.push({id:socket.id,name:data.name,stake:data.stake,socketId:socket.id});io.emit('challenges_list',openChallenges);io.emit('new_challenge',{name:data.name,stake:data.stake});});socket.on('cancel_challenge',()=>{openChallenges=openChallenges.filter(c=>c.socketId!==socket.id);io.emit('challenges_list',openChallenges);});socket.on('accept_challenge',(data)=>{const challenge=openChallenges.find(c=>c.id===data.challengeId);if(!challenge)return;openChallenges=openChallenges.filter(c=>c.id!==data.challengeId);io.emit('challenges_list',openChallenges);const matchId=challenge.socketId+'_'+socket.id;const discs=createDiscs();activeMatches[matchId]={player1:challenge.socketId,player2:socket.id,stake:challenge.stake,score:[0,0],ball:{x:170,y:290,vx:0,vy:0,r:BALL_R},discs,goalCooldown:0,turn:0,wasStopped:true};io.to(challenge.socketId).emit('match_start',{matchId,role:'player1',opponent:data.name,stake:challenge.stake});io.to(socket.id).emit('match_start',{matchId,role:'player2',opponent:challenge.name,stake:challenge.stake});setTimeout(()=>runMatchLoop(matchId),500);});socket.on('player_move',(data)=>{const match=activeMatches[data.matchId];if(!match)return;const disc=match.discs.find(d=>d.id===data.discId);if(!disc)return;disc.vx=data.vx;disc.vy=data.vy;});socket.on('disconnect',()=>{openChallenges=openChallenges.filter(c=>c.socketId!==socket.id);io.emit('challenges_list',openChallenges);});});
const PORT = process.env.PORT || 3000;
server.listen(PORT, () => { console.log('Server koer paa port ' + PORT); });
